name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  envied: ^1.1.1 # environment paketi
  equatable: ^2.0.7 # model paketi classları oluştururken immutable yapmak için
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17  # svg paketi
  json_annotation: ^4.9.0 # json parse paketi
  lottie: ^3.3.1 

dev_dependencies:
  build_runner: ^2.3.3 # build paketi
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.9.0 # image paketi
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0 # json parse paketi
  very_good_analysis: ^7.0.0 # analysis paketi
# geneartion işlemi için

flutter_gen:
  output: lib/src/asset/
  integrations:
#lottiflies.com dan aldığım lottie dosyalarının build edilmesi için
    lottie: true
    flutter_svg: true
# benim kök klosorde bulunan assets içindeki colors klorundeki xml dosyamdaki renkleri build ederek alttaki pathte kullanabileceğim şekilde hazırlıyor
  colors:
    inputs:
      - assets/color/colors.xml

 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/color/
    - assets/lottie/
    - assets/images/
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
