name: flutter_architectural_approach_example
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  # auto_route: bir çözümleri olmadığından ana projede olacak.
  auto_route: ^9.3.0+1
  common:
    path: module/common
  core:
    path: module/core
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  easy_localization: ^3.0.7+1 # localizasyon paketi
  # utility paketler
  easy_logger: ^0.0.2

  equatable: ^2.0.7 # model paketi classları oluştururken immutable yapmak için
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1 # state management paketi 
  gen:
    path: module/gen
  google_fonts: ^6.2.1

  kartal: ^4.1.0 # extensions paketi
  logger: ^2.5.0
  vexana: ^5.0.3 # network paketi
  widgets:
    path: module/widgets

# dependency_overrides: burasıda paketlerinin versiyonlarını ovvired ederiz. örneğin flutter_bloc 5.0.0 versiyonu ile çalışıyor. ama flutter_bloc 6.0.0 versiyonu ile çalışıyor. bu yüzden dependency_overrides ile 5.0.0 versiyonunu kullanıyoruz.

dev_dependencies:
# burası proje içeriisnde olacak ama realse alırken proje dışında olacak paketler yazılır.
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.3 # icon paketi
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0 # json parse paketi
  very_good_analysis: ^7.0.0 # analysis paketi
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true 

flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
