// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart
// This file is generated by the script/lang.sh file.
// ignore_for_file: public_member_api_docs, constant_identifier_names

abstract class LocaleKeys {
  static const home_title = 'home.title';
  static const home = 'home';
  static const general_button_cancel = 'general.button.cancel';
  static const general_button_ok = 'general.button.ok';
  static const general_button_yes = 'general.button.yes';
  static const general_button_no = 'general.button.no';
  static const general_button_save = 'general.button.save';
  static const general_button = 'general.button';
  static const general_dialog_version_title = 'general.dialog.version.title';
  static const general_dialog_version_content =
      'general.dialog.version.content';
  static const general_dialog_version = 'general.dialog.version';
  static const general_dialog = 'general.dialog';
  static const general = 'general';
}
